# Generated by Django 3.1.4 on 2020-12-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, error_messages={'blank': "The category_id field can't be blank.", 'invalid': 'The category_id field is invalid.', 'null': "The category_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_end',
            field=models.PositiveIntegerField(blank=True, error_messages={'blank': "The salary_end field can't be blank.", 'invalid': 'The salary_end field is invalid.', 'null': "The salary_end field can't be null."}, null=True, verbose_name='Salary up'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_start',
            field=models.PositiveIntegerField(blank=True, error_messages={'blank': "The salary_start field can't be blank.", 'invalid': 'The salary_start field is invalid.', 'null': "The salary_start field can't be null."}, null=True, verbose_name='Salary from'),
        ),
    ]
