# Generated by Django 3.1.4 on 2020-12-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201219_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, error_messages={'blank': "The country_id field can't be blank.", 'invalid': 'The country_id field is invalid.', 'null': "The country_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.country'),
        ),
    ]
