# Generated by Django 3.1.4 on 2020-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201219_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='COL', error_messages={'blank': "The code field can't be blank.", 'invalid': 'The code field is invalid.', 'max_length': 'The code field must be at most 255 characters.', 'null': "The code field can't be null."}, max_length=3, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
